name       : python-singledispatch
version    : 3.4.0.3
release    : 1
source     :  
    - https://pypi.python.org/packages/source/s/singledispatch/singledispatch-3.4.0.3.tar.gz : 5b06af87df13818d14f08a028e42f566640aef80805c3b50c5056b086e3c2b9c

license    : BSD-2-Clause
summary    : This library brings functools.singledispatch from Python 3.4 to Python 2.6-3.3.
description: |
    Transforms a function into a single-dispatch generic function.
builddeps  : 
    - python-setuptools
build      : |
    python setup.py build -b man
install    : |
    python setup.py install --root=$installdir/ --optimize=1
