name       : python-singledispatch
version    : 3.7.0
release    : 3
source     :
    - https://pypi.python.org/packages/source/s/singledispatch/singledispatch-3.7.0.tar.gz : c1a4d5c1da310c3fd8fccfb8d4e1cb7df076148fd5d858a819e37fffe44f3092
license    : BSD-2-Clause
component  : programming.python
summary    : This library brings functools.singledispatch from Python 3.4 to Python 2.6-3.3.
description: |
    Transforms a function into a single-dispatch generic function.
builddeps  :
    - python-setuptools
rundeps    :
    - python-six
setup      : |
    %python_setup
install    : |
    %python_install
